### ISSUE TITLE
Plot legend: use a fixed width

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-components#166]
This will ensure that the plot itself is the same size, regardless of label size.

**Comment by bobular** [comment]
Linking to @moontrip's #170  PR because I think we agreed that was a good enough legend fix for Phase 1.

**Comment by nkittur-uga** [comment]
On QA, I find that Plot legends do NOT have a fixed width and change in size depending on the length of the label. Screenshots added as examples of short and long label. We need clarification from the developers about what decisions were made regarding fixing this behavior since it is not fixed in QA.


<img width="847" alt="Screen Shot 2021-08-18 at 4 16 07 PM" src="https://user-images.githubusercontent.com/67710160/129966479-aa923f43-99b5-468e-8d48-2bd4440c53c8.png">
<img width="877" alt="Screen Shot 2021-08-18 at 4 16 35 PM" src="https://user-images.githubusercontent.com/67710160/129966482-e2996fb3-f84d-4a21-a27d-2a00bbe2f65c.png">

**Comment by moontrip** [comment]
Hi @nkittur-uga, thank you for your review. Actually this is different issue from legend. We have introduced legend ellipsis with tooltip, which longer text (20 characters for now) is changed with, e.g., 'trucatedtext...' format (please see an example screenshot in the following). The issue you have observed is long legend title, not legend, which is different each other. We have not considered legend title's ellipsis with tooltip so if you think it needs to be addressed, then new ticket/issue should be made.

![legend-ellipsis](https://user-images.githubusercontent.com/12802305/129968027-4f8940ee-2b22-40da-b8cb-78116b723102.png)

**Comment by nkittur-uga** [comment]
Ah! Thanks for the clarification, @moontrip , I understand that I did not QA the right thing. Let me go QA the legend (the correct issue) and ask my team about this legend label issue, if we need a new ticket for that or not.

**Comment by nkittur-uga** [comment]
Tried this on GEMS1 with x=weight, y=height, overlay=water availability, (and also with overlay= drinking water container) and it worked well. Long values are truncated with ellipses and you can hover to see complete label. This passes QA and can be closed.

**Comment by moontrip** [comment]
@nkittur-uga thanks again for your review 👍 The figure size of plotly is a bit strange and it is affected by legend title and legend as you noticed. Since there are many overlay variables that have relatively lengthy displayName, my feeling is that the legend title also needs to have a fixed width like introducing ellipsis with tooltip as legend was treated.

**Comment by bobular** [comment]
Needs a ticket then - I will make it :-)

**Comment by nkittur-uga** [comment]
Thanks @bobular for making a ticket (I was about to, but you beat me to it) :) 

@moontrip Agreed that legend title would need a fixed width but would request the label (display name) to be wrapped text if possible, instead of ellipsis with tooltip.

**Comment by moontrip** [comment]
@nkittur-uga thank you for your information. I think wrapped text means like multiple lines? Not quite sure if it is doable but will see at first. If not possible, we would need ellipsis with tooltip (for now)

**Comment by nkittur-uga** [comment]
@moontrip Yes, exactly, wrapping the text to cover multiple lines. And yes if that is not easily possible, ellipsis with tooltip will be great. Thanks.

**Comment by bobular** [comment]
Best to make these comments on the new ticket!
