### ISSUE TITLE
Visualizations: move Y-axis labels in RxC plot

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-components#184]
Move Y-axis labels to the left axis rather than in the legend, and center based on the boxes in the first row. May need additional UI work if there are many values for the Y-axis and the first row (X-axis value) doesn't have some of those values, since there will be no box for it. 
Users should not be able to remove one of the values for the axis.

**Comment by chowington** [comment]
Hi Sheena! Do you envision the y-axis labels being to the right of the numbers, to the right of the variable name, or to the left of the variable name?

![image](https://user-images.githubusercontent.com/12377649/130132141-0aaa9da2-52ac-4304-95b7-dee27bc11dc5.png)

There certainly will be an issue with boxes in the first column that are too small for either the label to fit or the color to be visible. I don't think we can lose the square color indicators present in the current legend. These are going to be challenges from an implementation perspective as well.

**Comment by SheenaTomko** [comment]
Yeah there are definitely challenges here and @d-callan can weigh in as well. I think we want something like this where we loose the y-axis scale and have the labels there instead. I could see there being an issue with long value labels pushing the variable label too far to the left unless we truncate the labels. In the case that there are boxes in the first column that are too small for the label or the color isn't visible, would it be possible to draw a short line from the label to where that box would be, so the labels could still be in the same order as the values, but offset if needed? And if you moused over the label, could it highlight all associated boxes for the user?

![image](https://user-images.githubusercontent.com/54597319/130134090-7e99f662-7da6-4611-a1f9-422cf6e0b30f.png)

**Comment by chowington** [comment]
@SheenaTomko Spent some more time thinking about this---it would certainly be a problem. Consider this mosaic with hover labels:

![image](https://user-images.githubusercontent.com/12377649/131231081-d249d943-f802-4a89-b67e-e9734983c36b.png)

The left-hand y-axis labels you describe are essentially these hover labels but always visible. In the image the tiny boxes at the bottom correspond to a lot of vertical space taken up by labels. You can image this getting even worse, such that the labels take up more vertical space than the whole plot itself. That's fine with hover labels because they're usually hidden, but these axis labels would always be visible. I don't think that's feasible.

I think this is no longer just an implementation problem. It's a UI problem that needs to be sorted out before talking about implementation issues.

**Comment by d-callan** [comment]
So I don't mind if we punt on this for now I suppose, though I think we should drop the numeric scale either way and probably leave the ticket open. And if I'm honest, I don't really see how any of these issues are specific to the y-axis. I think we'll have these problems on the x-axis too potentially, so I didnt think we were introducing new challenges. Though I get it increases the magnitude or urgency of the problem...

**Comment by chowington** [comment]
Assigning to @SheenaTomko (and others by extension) for UI discussion

**Comment by chowington** [comment]
@danicahelb Any comments on the above? If not, I'll assume these minor differences are fine

**Comment by aaronwlsong** [comment]
Y-axis now looks good now, closing ticket. 

![image](https://user-images.githubusercontent.com/61077845/141196335-329b2501-4d00-438b-b4a0-f771786f46ee.png)

![image](https://user-images.githubusercontent.com/61077845/141196569-a11ee568-15dd-4a0f-978b-4144527cc398.png)

![image](https://user-images.githubusercontent.com/61077845/141196905-8a5b274c-4544-4eba-9bf0-35bd6336564b.png)
