### ISSUE TITLE
Fix map chart markers SVG code to handle logscale prop

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-components#380]
To follow the latest work on viz axes, ranges, logscale and truncation: https://github.com/VEuPathDB/web-eda/pull/1241

Maps in SCORE Mozambique (for example)

The mouse-over bar charts are correctly showing the log scale. The SVG mini chart markers need to take into account the log transformation.

**Comment by moontrip** [comment]
@bobular I tried to address this but I could not make an appropriate solution because there seems no way to handle log scale using the pure SVG. This would probably need to use a graph lib like Plotly etc. to address. However, as we observed with Connor's histrogram approach for the chart marker in the beginning of the react map work, its use would make map slower, which was the reason why we used SVG chart marker instead.

In an attempt to address this in a simpler way with some degree of error, I made two draft PRs at web-eda and web-components respectively, https://github.com/VEuPathDB/web-eda/pull/1290 & https://github.com/VEuPathDB/web-components/pull/381. It may be used to minimize a visual gap between small (marker) and large (using mouse tool's magnification) charts for the time being, if necessary: it is more accurate for count option (plot mode) than proportion option, I suppose.

**Comment by bobular** [comment]
Hi @moontrip - one problem is that the current code does not honour `dependentAxisRange.min` properly.  I am attaching some sketches I made for the calculation of `barHeight`.  `R_min` and `R_max` are the values of `dependentAxisRange`.  Note that the calculations are basically the same in both cases, but with logScale active, the value, and `R_mn` and `R_max` are all logged.

It would be great also to get rid of the copy-paste duplication resulting from the `if (globalMaxValue) ... else `. It looks to me identical except for in one case there's a global axis range, and in the other a local one.

![00-no-logs](https://user-images.githubusercontent.com/308639/182680241-6bc52e90-0b1e-4d94-af45-147104fd1a6e.jpg)
![01-with-logs](https://user-images.githubusercontent.com/308639/182680234-217a78f4-2ccf-4fa8-8c18-212d93c1c50e.jpg)

**Comment by moontrip** [comment]
@bobular Thank you for taking time to think about this. Most of all, we do not have axis range control for mapViz. 😄 I have checked that we only have two kinds of controls for mapViz, plot mode and y-axis log scale (under the branch of viz-log-range-truncation)

**Comment by bobular** [comment]
That's correct there is no current y axis range control for mapviz, so the
`range.min` is always zero or I think usually 0.1 in logscale mode
(definitely in our massive axis PR which I will be merging today hopefully).

However, the EDA sets a uniform dependentAxisRange for all markers and the
ChartMarker component should be ready to handle the `range.min` in the
future. Though as you can see it is non-zero in logscale mode and so the
formulae I suggested should be implemented now.

**Comment by moontrip** [comment]
@bobular thank you for clarifying it. 👍 Your logic to deal with dependentAxisRange makes sense so I reflected it in the new commit. Several other parts were also adjusted, e.g., simplifying global and local max as you suggested, removed global max & proportionMode, etc. Please check https://github.com/VEuPathDB/web-components/pull/381 for updates

**Comment by SheenaTomko** [comment]
I think this is working as intended now
