### ISSUE TITLE
Finalize gradient colormaps

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-components#442]
Discussed in recent data viz meetings, can we improve readability of our gradient colormaps by lightening or darkening them?

Work towards this goal started in #434

**Comment by asizemore** [comment]
Decided on a light version of Berlin for converging and the original Vik for diverging.

Vik is currently used in web-components. Until there are overlay controls, a user cannot switch to Berlin anyways. So adding the converging colormap does not need to be complete until we have overlay controls scheduled

**Comment by asizemore** [comment]
Closed with #434

**Comment by SheenaTomko** [comment]
From Ann:
The convergent colormaps are added to the code base but without Overlay Controls, the user can't actually access them yet. And in the data viz meeting we decided to keep our diverging palette the same. So actually I'd say as long as nothing looks broken, then that's really all we can hope for with this ticket. 

Originally we expected to be modifying the diverging gradient colormap and such but turns out we were happy with what we have so there wasn't any work that would show up on the site as new.

QC: tested overlays of continuous variables in DailyBaby beta diversity app and it seemed to work
